/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.kenhkan.timoodstocks;

import android.app.Activity;
import android.view.SurfaceView;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.TiApplication;

import com.moodstocks.android.MoodstocksError;
import com.moodstocks.android.Result;
import com.moodstocks.android.ScannerSession;


@Kroll.proxy(creatableInModule=TimoodstocksModule.class)
public class ScannerView extends TiViewProxy implements
	ScannerSession.Listener
{
	// Standard Debugging variables
	private static final String TAG = "ScannerView";

	private int ScanOptions = Result.Type.IMAGE;
	private ScannerSession session;

	public ScannerView()
	{
		super();
	}

	//----------------------
	// The UI view itself
	//----------------------

	private class ScannerUIView extends TiUIView
	{
		public ScannerUIView(ScannerView proxy) {
			super(proxy);

      // Get current activity
      TiApplication appContext = TiApplication.getInstance();
      Activity activity = appContext.getCurrentActivity();

      // Create view for camera preview
      SurfaceView preview = new SurfaceView(activity);

      // Create a scanner session
      try {
        session = new ScannerSession(activity, (ScannerSession.Listener) proxy, preview);
      } catch (MoodstocksError error) {}

      // Set session options
      session.setOptions(ScanOptions);

      // Add view
			setNativeView(preview);
		}

		@Override
		public void processProperties(KrollDict d)
		{
			super.processProperties(d);
		}
	}

	@Override
	public TiUIView createView(Activity activity)
	{
		TiUIView view = new ScannerUIView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	//-------------------------
	// ScannerSession.Listener
	//-------------------------

	@Override
	public void onScanComplete(Result result) {
	}

	@Override
	public void onScanFailed(MoodstocksError error) {
	}

	@Override
	public void onApiSearchStart() {
	}

	@Override
	public void onApiSearchComplete(Result result) {
	}

	@Override
	public void onApiSearchFailed(MoodstocksError e) {
	}
}
